### ISSUE TITLE
NextEngine Not working

### ISSUE THREAD

**Issue by Smurfboi007** [nulli0n/ExcellentShop-spigot-old#12]
18.04 09:19:43 [Server] INFO [NexEngine] Enabling NexEngine v2.1.1 build-11/02/2022
18.04 09:19:43 [Server] WARN java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_18_R2
18.04 09:19:43 [Server] WARN at java.base/java.lang.Enum.valueOf(Enum.java:273)
18.04 09:19:43 [Server] WARN at NexEngine.jar//su.nexmedia.engine.Version.valueOf(Version.java:6)
18.04 09:19:43 [Server] WARN at NexEngine.jar//su.nexmedia.engine.Version.<clinit>(Version.java:19)
18.04 09:19:43 [Server] WARN at NexEngine.jar//su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:99)
18.04 09:19:43 [Server] WARN at NexEngine.jar//su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:70)
18.04 09:19:43 [Server] WARN at NexEngine.jar//su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:67)
18.04 09:19:43 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
18.04 09:19:43 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
18.04 09:19:43 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
18.04 09:19:43 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
18.04 09:19:43 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
18.04 09:19:43 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
18.04 09:19:43 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
18.04 09:19:43 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
18.04 09:19:43 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
18.04 09:19:43 [Server] ERROR Error occurred while enabling NexEngine v2.1.1 build-11/02/2022 (Is it up to date?)
18.04 09:19:43 [Server] INFO java.lang.ExceptionInInitializerError: null
18.04 09:19:43 [Server] INFO at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:99) ~[NexEngine.jar:?]
18.04 09:19:43 [Server] INFO at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:70) ~[NexEngine.jar:?]
18.04 09:19:43 [Server] INFO at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:67) ~[NexEngine.jar:?]
18.04 09:19:43 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.04 09:19:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.04 09:19:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
18.04 09:19:43 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-290]
18.04 09:19:43 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-290]
18.04 09:19:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-290]
18.04 09:19:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-290]
18.04 09:19:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-290]
18.04 09:19:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
18.04 09:19:43 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_18_R2
18.04 09:19:43 [Server] INFO at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
18.04 09:19:43 [Server] INFO at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[NexEngine.jar:?]
18.04 09:19:43 [Server] INFO at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[NexEngine.jar:?]
18.04 09:19:43 [Server] INFO ... 12 more
18.04 09:19:43 [Server] INFO [NexEngine] Disabling NexEngine v2.1.1 build-11/02/2022

**Comment by nulli0n** [comment]
Fixed in the latest builds.
