### ISSUE TITLE
Armor Stand Entities Bug on Restart when using Lands Plugin on Spigot

### ISSUE THREAD

**Issue by AmphyEX** [nulli0n/ExcellentShop-spigot-old#15]
When creating a shop within a Lands claim when using the Lands Plugin, upon stopping the server and restarting it, the old entity will freeze and be unable to update, but a new entity will overlap the old one, causing a weird visual bug. If you delete the shop, the old frozen entities will not be deleted and must manually be deleted with a /kill command.

**Comment by nulli0n** [comment]
Fixed in the latest versions.
